articles/urls.py
from django.urls import path, include, register_converter
from . import views, converters

register_converter(converters.UsernameProfileConverter, 'user')

app_name = 'articles'
urlpatterns = [
    path('home/', views.HomeView.as_view(), name='home'),
    path('create_article/', views.CreateArticleView.as_view(), name='create-article'),

    path('article/<user:author>/<slug:slug>/', include([
        path('edit_article/', views.UpdateArticleView.as_view(), name='edit-article'),
        path('delete/', views.DeleteArticleView.as_view(), name='delete-article'),
        path('add_comment/', views.add_comment, name='add-comment'),
        path('', views.ArticleDetailsView.as_view(), name='details'),
        
    ])),

    path('article/like_article/', views.like_article, name='like-article'),
    path('article/like_comment', views.like_comment, name='like-comment'),
]   

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('articles.urls')),
    path('auth/', include('authentication.urls')),
    path('admin/', admin.site.urls),
]

articles/models.py
from django.db import models

from django.utils.timezone import now
from django.urls import reverse


from authentication.models import Profile

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=20)

class Article(models.Model):

    title = models.CharField(max_length=255 ,blank=False)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)

    # note that now is used without parenthesis that is because 
    # with them default value is set to the time models.py is run
    pub_date = models.DateField(default=now)  
    last_edit_date = models.DateField(blank=True, null=True)
    slug = models.SlugField(unique=True, blank=False)

    text_body = models.TextField(verbose_name="text")
    sources = models.TextField(verbose_name="Sources", blank=True)
    sug_literature = models.TextField(verbose_name="Suggested Literature", blank=True)

    likes = models.ManyToManyField(Profile, related_name="liked_articles", blank=True)
    dislikes = models.ManyToManyField(Profile, related_name='disliked_articles', blank=True)
    bookmarks = models.ManyToManyField(Profile, related_name="bookmarked_articles", blank=True)
    
    tags = models.ManyToManyField(Tag, related_name='tagged_articles', blank=True, null=True)


    def get_absolute_url(self):
        return reverse('articles:details', kwargs={"author":self.author, "slug":self.slug})
    

    # used to show only part of a text in html template
    def get_preview(self):
        preview = self.text_body.split()[:50]
        preview = ' '.join(preview) + "..."
        return preview


class Comment(models.Model):
    
    related_article = models.ForeignKey(Article, related_name="comments", on_delete=models.CASCADE)
    author = models.ForeignKey(Profile, related_name="my_comments", on_delete=models.CASCADE, null=True)

    comment_text = models.TextField()

    likes = models.ManyToManyField(Profile, related_name="liked_comments")
    dislikes = models.ManyToManyField(Profile)

articles/views.py
from django.contrib.auth.decorators import login_required
from django.forms import ModelForm
from django.utils.text import slugify
from django.utils.timezone import now
from django.shortcuts import render
from django.urls import reverse, reverse_lazy

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin


from . import models

# Create your views here.

# refactor + add login constaint
def like_article(request):
    article_id = request.POST.get('like', False) or request.POST['dislike'] # if "like" in dict it doesn't check "dislike", if "dislike" in dict then gets article_id
    user = request.user
    article = models.Article.objects.get(pk=article_id)
    profile = user.profile

    if 'like' in request.POST:
        if profile in article.likes.all():     
            article.likes.remove(profile)
        else:
            article.likes.add(profile)
            article.dislikes.remove(profile)

    elif 'dislike' in request.POST:
        if profile in article.dislikes.all():     
            article.dislikes.remove(profile)
        else:
            article.dislikes.add(profile)
            article.likes.remove(profile)

    return HttpResponseRedirect(reverse('articles:home'))


def like_comment(request):
    comment_id = request.POST.get('like', False) or request.POST['dislike']
    user = request.user
    profile = user.profile
    comment = models.Comment.objects.get(pk=comment_id)
    slug = comment.related_article.slug

    if 'like' in request.POST:
        if profile in comment.likes.all():     
            comment.likes.remove(profile)
        else:
            comment.likes.add(profile)
            comment.dislikes.remove(profile)
            

    if 'dislike' in request.POST:
        if profile in comment.dislikes.all():     
            comment.dislikes.remove(profile)
        else:
            comment.dislikes.add(profile)
            comment.likes.remove(profile)

    return HttpResponseRedirect(reverse('articles:details', 
                                         kwargs={'author':profile, 
                                                 'slug':slug}))


def add_comment(request, author, slug):
    author_profile = author
    commenter_profile = request.user.profile
    related_article = models.Article.objects.get(author=author_profile, slug=slug)
    comment_text = request.POST['comment_text']

    comment = models.Comment.objects.create(author=commenter_profile, 
                                            related_article=related_article,    
                                            comment_text=comment_text)
    
    return HttpResponseRedirect(reverse('articles:details', 
                                         kwargs={'author':author_profile,
                                                 'slug':slug}))


class HomeView(ListView):
    model = models.Article
    template_name = 'articles/home_template.html'

    
class ArticleDetailsView(DetailView):
    model = models.Article
    template_name = 'articles/details_page.html'
    context_object_name = 'article'

    # takes arguments passed to the url and filters articles by their value
    def get_queryset(self):
        profile = self.kwargs['author']
        slug = self.kwargs['slug']

        return models.Article.objects.filter(slug=slug, author=profile)


class CreateArticleView(LoginRequiredMixin, CreateView):
    model = models.Article
    template_name = 'articles/create_article.html'
    fields = ['author', 'title', 'text_body', 'sources', 'sug_literature']

    # turns article title into a slug and assigns it to the slug field
    def form_valid(self, form):
        form.instance.slug = slugify(self.request.POST['title'])

        return super().form_valid(form)


class UpdateArticleView(UpdateView):
    model = models.Article
    template_name = 'articles/edit_article.html'
    fields = ['title', 'text_body', 'sources', 'sug_literature']

    # automatically sets last edit date for the article
    def form_valid(self, form):
        form.instance.last_edit_date = now()

        return super().form_valid(form)
    
    # default get_object method has to be overridden otherwise it doesn't behave 
    # properly while prepopulating form fields in editing view 
    def get_object(self):
        slug = self.kwargs['slug']
        profile = self.kwargs['author']

        return models.Article.objects.get(author=profile, slug=slug)
        

class DeleteArticleView(DeleteView):
    model = models.Article
    success_url = reverse_lazy('articles:home')

articles/templates/articles/create_article.html
<!DOCTYPE html>
<html>
    <head>

    </head>

    <body>
        <h1>CREATE ARTICLE</h1>

        
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}
            <input type="submit" value="Create">

        </form>
    

    </body>
</html>

articles/templates/articles/details_page.html
<!DOCTYPE html>
<html>
    <head>
        {% load markdown_tags %}
    </head>

    <body>
        <h1>DETAILS</h1>


        <div>
            <h2>{{ article.title }}</h2>

            <div>
                <p>{{ article.text_body|markdown|safe }}</p> 
            </div>

            <div>
                <h3>sources</h3>
                <p>{{ article.sources|markdown|safe }}</p> 
            </div>

            <div>
                <h3>suggested literature</h3>
                <p>{{ article.suggested_literature|markdown|safe }}</p>
            </div>

            <div>
                <h3>Edited</h3>
                <p>last edited - {{ article.last_edit_date }}</p>
            </div>
        </div>
        

        <div>
            <form method="post" action="{% url 'articles:delete-article' article.author article.slug %}">
                {% csrf_token %}
                <input type="submit" value="delete">
            </form>
    
            <form action="{% url 'articles:edit-article' article.author article.slug %}">
                {% csrf_token %}
                <input type="submit" value="edit">
            </form>
        </div>

        <hr>
        <br> 
        

        <div>
            <form method="post" action="{% url 'articles:add-comment' article.author article.slug %}">
                {% csrf_token %}
                <input type="text" name="comment_text">
                <input type="submit" value="send">
            </form>

            <div>
                {% for comment in article.comments.all %}

                <div>
                    <h3>{{ comment.author }}</h3>
                    <p>{{ comment.comment_text }}</p>

                    <form method="post" action="{% url 'articles:like-comment' %}">
                        {% csrf_token %}

                        <button name="like" value="{{ comment.id }}">LIKE</button>
                        <label>{{ comment.likes.all|length }}</label>

                        <button name="dislike" value="{{ comment.id }}">DISLIKE</button>
                        <label>{{ comment.dislikes.all|length }}</label>
                    </form>

                    <hr>
                </div>   
                
                {% endfor %}
            </div>
        </div>
         

    </body>
</html>

articles/templates/articles/edit_article.html
<!DOCTYPE html>
<html>
    <head>

    </head>

    <body>
        <h1>EDIT ARTICLE</h1>

        <form method="post">
            {% csrf_token %}
            
            {{ form.as_p }}
            <input type="submit" value="Create">
            
        </form>

    </body>
</html>

articles/templates/articles/home_template.html
<!DOCTYPE html>
<html>
    <head>
        {% load markdown_tags %}
        {% load static %}
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@700&display=swap" rel="stylesheet">

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Cardo&display=swap" rel="stylesheet">

        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
        
        <link href="{% static 'articles/home.css' %}" rel="stylesheet" type="text/css">
    </head>

    <body>
        <h3 style="color: red;">Logged in as: {{ request.user.username }}</h3>

        <div class="container">
            {% for article in object_list %}

                <div class="container__card">

                    <div class="article-preview">
                        <h2><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h2>
                        <h4>useful for when you need to use a URL reversal before your projec</h4>
                        <h3>by {{ article.author }}</h3>
                        <p>{{ article.get_preview|markdown|safe }}</p> 
                    </div> 

                    

                    <div class="reactions">
                        <h3>tags: </h3>
                        <form method="post" action="{% url 'articles:like-article' %}">
                            {% csrf_token %}
        
                            <button id="like-btn" name="like" value="{{ article.id }}">
                                <span class="material-symbols-outlined">
                                    keyboard_arrow_up
                                </span>
                            </button>
                            <label for="#like-btn">{{ article.likes.all|length }}</label>
        
                            <button id="dislike-btn" name="dislike" value="{{ article.id }}">
                                <span class="material-symbols-outlined">
                                    keyboard_arrow_down
                                </span>
                            </button>
                            <label for="#dislike-btn">{{ article.dislikes.all|length }}</label>
        
                        </form>
                    </div>
                    <br> 

                </div>

            {% endfor%}  
        </div>
           

    </body>
</html>